spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cqoj
    username: root
    password: 111111
  redis:
    database: 4
    host: 192.168.3.128
    port: 6379
    password: 123321
    timeout: 5000
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: fk3kEpTnepF4dfbs

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

aliyun:
  oss:
    access-key: XXX
    key-secret: XXX
    bucket-name: XXX
    endpoint: XXX
